# <b><i><u>STUDENT MENTAL HEALTH SURVEY </U>----</B></I>

In [1]:
# FOR PATH RECOGNISION ----

from pathlib import Path

print("Current Folder:")
print(Path.cwd())

print("\nParent:")
print(Path.cwd().parent)

Current Folder:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\students_mental_health_survey

Parent:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks


In [2]:
# IGNORE WARNING --

import warnings

warnings.filterwarnings("ignore")

In [3]:
# IMPORTING ALL THE NECESSARY LIBRARIES --

# Data Handling

import pandas as pd
import numpy as np

# Visualization

import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler,
    MinMaxScaler
)

# Train Test Split

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

# Models

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from xgboost import (
    XGBClassifier,
    XGBRegressor
)

# Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving

import joblib

# Display

pd.set_option(
    "display.max_columns",
    None
)

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

sns.set_style("whitegrid")

print("all the necessary libraries are imported sucessfully:")
print("🎉🎉🎉🎉")

all the necessary libraries are imported sucessfully:
🎉🎉🎉🎉


In [4]:
# PATH SETUP
# current notebook folder
CURRENT_DIR = Path.cwd()

# notebooks folder
NOTEBOOKS_DIR = CURRENT_DIR.parent

# project root
BASE_DIR = NOTEBOOKS_DIR.parent

# folders
PREPROCESSED_DIR = NOTEBOOKS_DIR / "preprocessed"
MODELS_DIR = NOTEBOOKS_DIR / "models"

PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# file path
DATA_PATH = PREPROCESSED_DIR / "students_mental_health_survey_model_ready.csv"

print("Current Dir:", CURRENT_DIR)
print("Notebooks Dir:", NOTEBOOKS_DIR)
print("Preprocessed Dir:", PREPROCESSED_DIR)
print("Models Dir:", MODELS_DIR)
print("Data Path:", DATA_PATH)

Current Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\students_mental_health_survey
Notebooks Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks
Preprocessed Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed
Models Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models
Data Path: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed\students_mental_health_survey_model_ready.csv


In [5]:
# LOADING DATASET --

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)
df.head()

Shape: (7022, 28)


,age,gender,cgpa,stress_level,depression_score,anxiety_score,sleep_quality,physical_activity,diet_quality,social_support,relationship_status,substance_use,counseling_service_use,family_history,chronic_illness,financial_stress,extracurricular_involvement,semester_credit_load,residence_type,course_Computer Science,course_Engineering,course_Law,course_Medical,course_Others,cgpa_risk,health_risk_score,social_risk_score,overall_risk_score
0,25,1,3.56,3,3,2,2,1,2,1,2,0,0,0,0,2,1,17,0,False,False,False,False,True,0.44,0,4,13.14
1,24,0,2.44,0,3,0,1,0,1,0,0,1,1,0,0,3,0,27,0,False,True,False,False,False,1.56,2,4,16.26
2,19,0,3.74,4,0,3,2,0,1,1,1,0,1,0,0,4,2,15,0,False,False,False,False,False,0.26,1,2,11.76
3,19,1,3.65,2,1,0,1,0,1,1,0,0,0,0,0,4,1,20,1,True,False,False,False,False,0.35,0,2,9.35
4,18,1,3.40,3,3,4,2,0,1,2,2,0,0,0,1,0,2,23,0,False,False,False,False,False,0.60,1,2,12.90


In [6]:
# BASIC INSPECTION --

print("Columns:")
print(df.columns.tolist())

print("\nInfo:")
print(df.info())

print("\nTarget distribution:")
print(df["stress_level"].value_counts().sort_index())

Columns:
['age', 'gender', 'cgpa', 'stress_level', 'depression_score', 'anxiety_score', 'sleep_quality', 'physical_activity', 'diet_quality', 'social_support', 'relationship_status', 'substance_use', 'counseling_service_use', 'family_history', 'chronic_illness', 'financial_stress', 'extracurricular_involvement', 'semester_credit_load', 'residence_type', 'course_Computer Science', 'course_Engineering', 'course_Law', 'course_Medical', 'course_Others', 'cgpa_risk', 'health_risk_score', 'social_risk_score', 'overall_risk_score']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7022 entries, 0 to 7021
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   age                          7022 non-null   int64  
 1   gender                       7022 non-null   int64  
 2   cgpa                         7022 non-null   float64
 3   stress_level                 7022 non-null   int64  
 4   de

In [7]:
# DEFINING X AND Y --

TARGET_COL = "stress_level"

X = df.drop(columns=[TARGET_COL])
y = df[TARGET_COL]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (7022, 27)
y shape: (7022,)


In [8]:
# FEATURE NAME --

feature_names = X.columns.tolist()

print("Total features:", len(feature_names))
feature_names[:20]

Total features: 27


['age',
 'gender',
 'cgpa',
 'depression_score',
 'anxiety_score',
 'sleep_quality',
 'physical_activity',
 'diet_quality',
 'social_support',
 'relationship_status',
 'substance_use',
 'counseling_service_use',
 'family_history',
 'chronic_illness',
 'financial_stress',
 'extracurricular_involvement',
 'semester_credit_load',
 'residence_type',
 'course_Computer Science',
 'course_Engineering']

In [9]:
# TRAIN TEST SPLIT --

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5617, 27)
X_test : (1405, 27)
y_train: (5617,)
y_test : (1405,)


# <B><U><I>MODEL 1 </U>----

In [10]:
# LOGGISTIC REGRESSION --

log_reg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=3000,
        random_state=42
    ))
])

In [11]:
log_reg_pipeline.fit(X_train, y_train)

,steps,"[('scaler', ...), ('model', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [12]:
# EVALUATION --

y_pred_lr = log_reg_pipeline.predict(X_test)

lr_acc = accuracy_score(y_test, y_pred_lr)
lr_f1 = f1_score(y_test, y_pred_lr, average="weighted")

print("Logistic Regression Accuracy:", round(lr_acc * 100, 2), "%")
print("Logistic Regression Weighted F1:", round(lr_f1, 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Accuracy: 21.99 %
Logistic Regression Weighted F1: 0.2183

Classification Report:

              precision    recall  f1-score   support

           0       0.20      0.24      0.22       220
           1       0.21      0.22      0.21       247
           2       0.18      0.15      0.16       256
           3       0.22      0.21      0.21       281
           4       0.24      0.32      0.28       198
           5       0.29      0.21      0.24       203

    accuracy                           0.22      1405
   macro avg       0.22      0.22      0.22      1405
weighted avg       0.22      0.22      0.22      1405


Confusion Matrix:

[[52 46 45 57 16  4]
 [50 54 49 50 29 15]
 [57 56 38 49 36 20]
 [40 49 41 59 62 30]
 [33 24 15 25 63 38]
 [26 28 22 30 54 43]]


# <B><I><U>MODEL 2</U> ----</B></I>

In [13]:
# RANDOM FOREST --

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [14]:
rf_model.fit(X_train, y_train)

,n_estimators,300
,criterion,'gini'
,max_depth,None
,min_samples_split,5
,min_samples_leaf,2
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [15]:
# EVALUATION --

y_pred_rf = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf, average="weighted")

print("Random Forest Accuracy:", round(rf_acc * 100, 2), "%")
print("Random Forest Weighted F1:", round(rf_f1, 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 20.64 %
Random Forest Weighted F1: 0.2052

Classification Report:

              precision    recall  f1-score   support

           0       0.24      0.25      0.24       220
           1       0.20      0.24      0.22       247
           2       0.15      0.13      0.14       256
           3       0.21      0.23      0.22       281
           4       0.22      0.21      0.21       198
           5       0.24      0.17      0.20       203

    accuracy                           0.21      1405
   macro avg       0.21      0.21      0.21      1405
weighted avg       0.21      0.21      0.21      1405


Confusion Matrix:

[[55 53 47 47 11  7]
 [37 60 52 61 23 14]
 [51 67 34 57 28 19]
 [40 53 47 64 43 34]
 [28 31 20 38 42 39]
 [21 29 33 39 46 35]]


# <B><U><I>MODEL 3</U> ----</B></I>

In [16]:
# XG_BOOST --

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="multi:softmax",
    num_class=len(np.unique(y)),
    random_state=42,
    eval_metric="mlogloss"
)

In [17]:
xgb_model.fit(X_train, y_train)

,objective,'multi:softmax'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,0.9
,device,None
,early_stopping_rounds,None
,enable_categorical,False
,eval_metric,'mlogloss'


In [18]:
# EVALUATION --

y_pred_xgb = xgb_model.predict(X_test)

xgb_acc = accuracy_score(y_test, y_pred_xgb)
xgb_f1 = f1_score(y_test, y_pred_xgb, average="weighted")

print("XGBoost Accuracy:", round(xgb_acc * 100, 2), "%")
print("XGBoost Weighted F1:", round(xgb_f1, 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_xgb))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_xgb))

XGBoost Accuracy: 20.07 %
XGBoost Weighted F1: 0.1999

Classification Report:

              precision    recall  f1-score   support

           0       0.21      0.24      0.22       220
           1       0.20      0.23      0.21       247
           2       0.16      0.16      0.16       256
           3       0.21      0.22      0.22       281
           4       0.20      0.17      0.19       198
           5       0.23      0.17      0.20       203

    accuracy                           0.20      1405
   macro avg       0.20      0.20      0.20      1405
weighted avg       0.20      0.20      0.20      1405


Confusion Matrix:

[[53 58 45 43 11 10]
 [49 56 49 49 26 18]
 [51 66 42 57 23 17]
 [46 50 54 63 35 33]
 [32 32 26 41 34 33]
 [24 25 39 44 37 34]]


In [19]:
# MODEL COMPARISON --

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        lr_acc,
        rf_acc,
        xgb_acc
    ],
    "Weighted_F1": [
        lr_f1,
        rf_f1,
        xgb_f1
    ]
})

results = results.sort_values(by=["Accuracy", "Weighted_F1"], ascending=False).reset_index(drop=True)
results

,Model,Accuracy,Weighted_F1
0,Logistic Regression,0.219929,0.218257
1,Random Forest,0.206406,0.205213
2,XGBoost,0.200712,0.199924


In [20]:
model_save_path = MODELS_DIR / "student_survey_stress_model.pkl"

joblib.dump(log_reg_pipeline, model_save_path)

print("Best model saved successfully")
print("Saved at:", model_save_path)

Best model saved successfully
Saved at: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models\student_survey_stress_model.pkl


FileNotFoundError: [Errno 2] No such file or directory: 'models/wellness_features.pkl'