# <b><i><u>STUDENT MENTAL HEALTH SURVEY </U>----</B></I>

In [1]:
# FOR PATH RECOGNISION ----

from pathlib import Path

print("Current Folder:")
print(Path.cwd())

print("\nParent:")
print(Path.cwd().parent)

Current Folder:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\students_mental_health_survey

Parent:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks


In [2]:
# IGNORE WARNING --

import warnings

warnings.filterwarnings("ignore")

In [3]:
# IMPORTING ALL THE NECESSARY LIBRARIES --

# Data Handling

import pandas as pd
import numpy as np

# Visualization

import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler,
    MinMaxScaler
)

# Train Test Split

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

# Models

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from xgboost import (
    XGBClassifier,
    XGBRegressor
)

# Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving

import joblib

# Display

pd.set_option(
    "display.max_columns",
    None
)

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

sns.set_style("whitegrid")

print("all the necessary libraries are imported sucessfully:")
print("🎉🎉🎉🎉")

all the necessary libraries are imported sucessfully:
🎉🎉🎉🎉


In [4]:
# PATH SETUP
# current notebook folder
CURRENT_DIR = Path.cwd()

# notebooks folder
NOTEBOOKS_DIR = CURRENT_DIR.parent

# project root
BASE_DIR = NOTEBOOKS_DIR.parent

# folders
PREPROCESSED_DIR = NOTEBOOKS_DIR / "preprocessed"
MODELS_DIR = NOTEBOOKS_DIR / "models"

PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# file path
DATA_PATH = PREPROCESSED_DIR / "students_mental_health_survey_model_ready.csv"

print("Current Dir:", CURRENT_DIR)
print("Notebooks Dir:", NOTEBOOKS_DIR)
print("Preprocessed Dir:", PREPROCESSED_DIR)
print("Models Dir:", MODELS_DIR)
print("Data Path:", DATA_PATH)

Current Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\students_mental_health_survey
Notebooks Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks
Preprocessed Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed
Models Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models
Data Path: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed\students_mental_health_survey_model_ready.csv


In [5]:
# LOADING DATASET --

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)
df.head()

Shape: (7022, 28)


,age,gender,cgpa,stress_level,depression_score,anxiety_score,sleep_quality,physical_activity,diet_quality,social_support,relationship_status,substance_use,counseling_service_use,family_history,chronic_illness,financial_stress,extracurricular_involvement,semester_credit_load,residence_type,course_Computer Science,course_Engineering,course_Law,course_Medical,course_Others,cgpa_risk,health_risk_score,social_risk_score,overall_risk_score
0,25,1,3.56,3,3,2,2,1,2,1,2,0,0,0,0,2,1,17,0,False,False,False,False,True,0.44,0,4,13.14
1,24,0,2.44,0,3,0,1,0,1,0,0,1,1,0,0,3,0,27,0,False,True,False,False,False,1.56,2,4,16.26
2,19,0,3.74,4,0,3,2,0,1,1,1,0,1,0,0,4,2,15,0,False,False,False,False,False,0.26,1,2,11.76
3,19,1,3.65,2,1,0,1,0,1,1,0,0,0,0,0,4,1,20,1,True,False,False,False,False,0.35,0,2,9.35
4,18,1,3.40,3,3,4,2,0,1,2,2,0,0,0,1,0,2,23,0,False,False,False,False,False,0.60,1,2,12.90


In [6]:
# BASIC INSPECTION --

print("Columns:")
print(df.columns.tolist())

print("\nInfo:")
print(df.info())

print("\nTarget distribution:")
print(df["stress_level"].value_counts().sort_index())

Columns:
['age', 'gender', 'cgpa', 'stress_level', 'depression_score', 'anxiety_score', 'sleep_quality', 'physical_activity', 'diet_quality', 'social_support', 'relationship_status', 'substance_use', 'counseling_service_use', 'family_history', 'chronic_illness', 'financial_stress', 'extracurricular_involvement', 'semester_credit_load', 'residence_type', 'course_Computer Science', 'course_Engineering', 'course_Law', 'course_Medical', 'course_Others', 'cgpa_risk', 'health_risk_score', 'social_risk_score', 'overall_risk_score']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7022 entries, 0 to 7021
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   age                          7022 non-null   int64  
 1   gender                       7022 non-null   int64  
 2   cgpa                         7022 non-null   float64
 3   stress_level                 7022 non-null   int64  
 4   de

In [7]:
# DEFINING X AND Y --

TARGET_COL = "stress_level"

X = df.drop(columns=[TARGET_COL])
y = df[TARGET_COL]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (7022, 27)
y shape: (7022,)


In [8]:
# FEATURE NAME --

feature_names = X.columns.tolist()

print("Total features:", len(feature_names))
feature_names[:20]

Total features: 27


['age',
 'gender',
 'cgpa',
 'depression_score',
 'anxiety_score',
 'sleep_quality',
 'physical_activity',
 'diet_quality',
 'social_support',
 'relationship_status',
 'substance_use',
 'counseling_service_use',
 'family_history',
 'chronic_illness',
 'financial_stress',
 'extracurricular_involvement',
 'semester_credit_load',
 'residence_type',
 'course_Computer Science',
 'course_Engineering']

In [9]:
# TRAIN TEST SPLIT --

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5617, 27)
X_test : (1405, 27)
y_train: (5617,)
y_test : (1405,)


# <B><U><I>MODEL 1 </U>----

In [10]:
# LOGGISTIC REGRESSION --

log_reg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=3000,
        random_state=42
    ))
])

In [11]:
log_reg_pipeline.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('model', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[int64](6,)","[0,1,2,3,4,5]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](27,)","['age','gender','cgpa',...,'health_risk_score','social_risk_score', 'overall_risk_score']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,27
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


In [12]:
# EVALUATION --

y_pred_lr = log_reg_pipeline.predict(X_test)

lr_acc = accuracy_score(y_test, y_pred_lr)
lr_f1 = f1_score(y_test, y_pred_lr, average="weighted")

print("Logistic Regression Accuracy:", round(lr_acc * 100, 2), "%")
print("Logistic Regression Weighted F1:", round(lr_f1, 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Accuracy: 21.99 %
Logistic Regression Weighted F1: 0.2183

Classification Report:

              precision    recall  f1-score   support

           0       0.20      0.24      0.22       220
           1       0.21      0.22      0.21       247
           2       0.18      0.15      0.16       256
           3       0.22      0.21      0.21       281
           4       0.24      0.32      0.28       198
           5       0.29      0.21      0.24       203

    accuracy                           0.22      1405
   macro avg       0.22      0.22      0.22      1405
weighted avg       0.22      0.22      0.22      1405


Confusion Matrix:

[[52 46 45 57 16  4]
 [50 54 49 50 29 15]
 [57 56 38 49 36 20]
 [40 49 41 59 62 30]
 [33 24 15 25 63 38]
 [26 28 22 30 54 43]]


# <B><I><U>MODEL 2</U> ----</B></I>

In [13]:
# RANDOM FOREST --

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [14]:
rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",300
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",5
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",2
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,:meth:`decision_path` and :meth:`apply` are all parallelized over thetrees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`context. ``-1`` means using all processors. See :term:`Glossary<n_jobs>` for more details.",-1
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total

In [15]:
# EVALUATION --

y_pred_rf = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf, average="weighted")

print("Random Forest Accuracy:", round(rf_acc * 100, 2), "%")
print("Random Forest Weighted F1:", round(rf_f1, 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 20.64 %
Random Forest Weighted F1: 0.2052

Classification Report:

              precision    recall  f1-score   support

           0       0.24      0.25      0.24       220
           1       0.20      0.24      0.22       247
           2       0.15      0.13      0.14       256
           3       0.21      0.23      0.22       281
           4       0.22      0.21      0.21       198
           5       0.24      0.17      0.20       203

    accuracy                           0.21      1405
   macro avg       0.21      0.21      0.21      1405
weighted avg       0.21      0.21      0.21      1405


Confusion Matrix:

[[55 53 47 47 11  7]
 [37 60 52 61 23 14]
 [51 67 34 57 28 19]
 [40 53 47 64 43 34]
 [28 31 20 38 42 39]
 [21 29 33 39 46 35]]


# <B><U><I>MODEL 3</U> ----</B></I>

In [16]:
# XG_BOOST --

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="multi:softmax",
    num_class=len(np.unique(y)),
    random_state=42,
    eval_metric="mlogloss"
)

In [17]:
xgb_model.fit(X_train, y_train)

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softmax'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API <callback_api>`... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.9
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import loa

In [18]:
# EVALUATION --

y_pred_xgb = xgb_model.predict(X_test)

xgb_acc = accuracy_score(y_test, y_pred_xgb)
xgb_f1 = f1_score(y_test, y_pred_xgb, average="weighted")

print("XGBoost Accuracy:", round(xgb_acc * 100, 2), "%")
print("XGBoost Weighted F1:", round(xgb_f1, 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_xgb))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_xgb))

XGBoost Accuracy: 20.07 %
XGBoost Weighted F1: 0.1999

Classification Report:

              precision    recall  f1-score   support

           0       0.21      0.24      0.22       220
           1       0.20      0.23      0.21       247
           2       0.16      0.16      0.16       256
           3       0.21      0.22      0.22       281
           4       0.20      0.17      0.19       198
           5       0.23      0.17      0.20       203

    accuracy                           0.20      1405
   macro avg       0.20      0.20      0.20      1405
weighted avg       0.20      0.20      0.20      1405


Confusion Matrix:

[[53 58 45 43 11 10]
 [49 56 49 49 26 18]
 [51 66 42 57 23 17]
 [46 50 54 63 35 33]
 [32 32 26 41 34 33]
 [24 25 39 44 37 34]]


In [19]:
# MODEL COMPARISON --

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        lr_acc,
        rf_acc,
        xgb_acc
    ],
    "Weighted_F1": [
        lr_f1,
        rf_f1,
        xgb_f1
    ]
})

results = results.sort_values(by=["Accuracy", "Weighted_F1"], ascending=False).reset_index(drop=True)
results

,Model,Accuracy,Weighted_F1
0,Logistic Regression,0.219929,0.218257
1,Random Forest,0.206406,0.205213
2,XGBoost,0.200712,0.199924


In [20]:
model_save_path = MODELS_DIR / "student_survey_stress_model.pkl"

joblib.dump(log_reg_pipeline, model_save_path)

print("Best model saved successfully")
print("Saved at:", model_save_path)

Best model saved successfully
Saved at: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models\student_survey_stress_model.pkl


In [23]:
print(type(log_reg_pipeline))

print(log_reg_pipeline)

print(hasattr(log_reg_pipeline, "predict_proba"))

<class 'sklearn.pipeline.Pipeline'>
Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=3000, random_state=42))])
True


In [24]:
pred = log_reg_pipeline.predict(X_test)

print(pred[:10])
print(pred.min())
print(pred.max())

[3 4 2 3 1 4 4 4 0 1]
0
5


In [25]:
print(df[y].head())

print(df[y].dtype)

print(df[y].value_counts().head(20))

KeyError: "None of [Index([3, 0, 4, 2, 3, 2, 2, 0, 3, 2,\n       ...\n       1, 0, 0, 5, 1, 3, 3, 4, 4, 3],\n      dtype='int64', length=7022)] are in the [columns]"